name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95 # v1.4.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: 'Checkout Repository'
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.0.0

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@23d1ffffb6fa5401173051ec21eba8c35242733f # v1
